export const dogBreedSelectOptions = [
  { label: "Akita", value: "Akita" },
  { label: "Alaskan Malamute", value: "Alaskan Malamute" },
  { label: "Australian Cattle Dog", value: "Australian Cattle Dog" },
  { label: "Australian Shepherd", value: "Australian Shepherd" },
  { label: "Basset Hound", value: "Basset Hound" },
  { label: "Beagle", value: "Beagle" },
  { label: "Belgian Malinois", value: "Belgian Malinois" },
  { label: "Belgian Sheepdog", value: "Belgian Sheepdog" },
  { label: "Bernese Mountain Dog", value: "Bernese Mountain Dog" },
  { label: "Bichon Frise", value: "Bichon Frise" },
  { label: "Border Collie", value: "Border Collie" },
  { label: "Border Terrier", value: "Border Terrier" },
  { label: "Boston Terrier", value: "Boston Terrier" },
  { label: "Boxer", value: "Boxer" },
  { label: "Bulldog", value: "Bulldog" },
  { label: "Cairn Terrier", value: "Cairn Terrier" },
  {
    label: "Cavalier King Charles Spaniel",
    value: "Cavalier King Charles Spaniel",
  },
  { label: "Chesapeake Bay Retriever", value: "Chesapeake Bay Retriever" },
  { label: "Chihuahua", value: "Chihuahua" },
  { label: "Chow Chow", value: "Chow Chow" },
  { label: "Collie", value: "Collie" },
  { label: "Cocker Spaniel", value: "Cocker Spaniel" },
  { label: "Dachshund", value: "Dachshund" },
  { label: "Doberman Pinscher", value: "Doberman Pinscher" },
  { label: "English Springer Spaniel", value: "English Springer Spaniel" },
  { label: "Finnish Lapphund", value: "Finnish Lapphund" },
  { label: "French Bulldog", value: "French Bulldog" },
  { label: "German Shepherd", value: "German Shepherd" },
  { label: "German Shorthaired Pointer", value: "German Shorthaired Pointer" },
  { label: "Golden Retriever", value: "Golden Retriever" },
  { label: "Great Dane", value: "Great Dane" },
  { label: "Havanese", value: "Havanese" },
  { label: "Irish Setter", value: "Irish Setter" },
  { label: "Irish Wolfhound", value: "Irish Wolfhound" },
  { label: "Jack Russell Terrier", value: "Jack Russell Terrier" },
  { label: "Keeshond", value: "Keeshond" },
  { label: "Labrador Retriever", value: "Labrador Retriever" },
  { label: "Lagotto Romagnolo", value: "Lagotto Romagnolo" },
  { label: "Lhasa Apso", value: "Lhasa Apso" },
  { label: "Maltese", value: "Maltese" },
  { label: "Mastiff", value: "Mastiff" },
  { label: "Miniature Schnauzer", value: "Miniature Schnauzer" },
  { label: "Neapolitan Mastiff", value: "Neapolitan Mastiff" },
  { label: "Newfoundland", value: "Newfoundland" },
  { label: "Papillon", value: "Papillon" },
  { label: "Pembroke Welsh Corgi", value: "Pembroke Welsh Corgi" },
  { label: "Pekingese", value: "Pekingese" },
  { label: "Pomeranian", value: "Pomeranian" },
  { label: "Pug", value: "Pug" },
  { label: "Puli", value: "Puli" },
  { label: "Rottweiler", value: "Rottweiler" },
  { label: "Saint Bernard", value: "Saint Bernard" },
  { label: "Saluki", value: "Saluki" },
  { label: "Shetland Sheepdog", value: "Shetland Sheepdog" },
  { label: "Shiba Inu", value: "Shiba Inu" },
  { label: "Shih Tzu", value: "Shih Tzu" },
  { label: "Siberian Husky", value: "Siberian Husky" },
  { label: "Toy Poodle", value: "Toy Poodle" },
  { label: "Tibetan Terrier", value: "Tibetan Terrier" },
  { label: "Weimaraner", value: "Weimaraner" },
  { label: "West Highland Terrier", value: "West Highland Terrier" },
  { label: "Whippet", value: "Whippet" },
  { label: "Yorkshire Terrier", value: "Yorkshire Terrier" },
];
