export const dogsSeedData = [
    {
        "email": "lisa@test.com",
        "breed": "Australian Shepherd",
        "username": "lisa",
        "gender": "female",
        "dateOfBirth": "2020-02-14",
        "name": "Lisa",
        "created": "2020-06-24",
        "lastActive": "2024-06-21",
        "description": "I love to play tug and hang out on the beach",
        "city": "San Diego",
        "country": "United States",
        "image": "/images/f1.jpeg"
    },
    {
        "email": "buddy@test.com",
        "breed": "Shar Pei",
        "username": "buddy",
        "gender": "male",
        "dateOfBirth": "2019-05-10",
        "name": "Buddy",
        "created": "2019-07-15",
        "lastActive": "2024-06-20",
        "description": "I'm a happy dog who loves to fetch balls",
        "city": "Austin",
        "country": "United States",
        "image": "/images/f2.jpeg"
    },
    {
        "email": "bella@test.com",
        "breed": "Cavalier King Charles Spaniel",
        "username": "bella",
        "gender": "female",
        "dateOfBirth": "2021-03-22",
        "name": "Bella",
        "created": "2021-05-30",
        "lastActive": "2024-06-18",
        "description": "I enjoy guarding my family and long walks",
        "city": "Los Angeles",
        "country": "United States",
        "image": "/images/f3.jpeg"
    },
    {
        "email": "max@test.com",
        "breed": "Husky",
        "username": "max",
        "gender": "male",
        "dateOfBirth": "2018-11-04",
        "name": "Max",
        "created": "2018-12-15",
        "lastActive": "2024-06-19",
        "description": "I love sniffing out new places and chasing rabbits",
        "city": "New York",
        "country": "United States",
        "image": "/images/f4.jpeg"
    },
    {
        "email": "daisy@test.com",
        "breed": "Australian Shepherd",
        "username": "daisy",
        "gender": "female",
        "dateOfBirth": "2017-07-29",
        "name": "Daisy",
        "created": "2017-09-10",
        "lastActive": "2024-06-15",
        "description": "I enjoy lounging on the couch and getting belly rubs",
        "city": "Miami",
        "country": "United States",
        "image": "/images/f5.jpeg"
    },

    {
        "email": "charlie@test.com",
        "breed": "Norwegian Elkhound",
        "username": "charlie",
        "gender": "male",
        "dateOfBirth": "2020-12-20",
        "name": "Charlie",
        "created": "2021-02-01",
        "lastActive": "2024-06-22",
        "description": "I love being groomed and showing off my fluffy coat",
        "city": "Chicago",
        "country": "United States",
        "image": "/images/m1.jpeg"
    },
    {
        "email": "rocky@test.com",
        "breed": "American Pitbull Terrier",
        "username": "rocky",
        "gender": "male",
        "dateOfBirth": "2019-08-17",
        "name": "Rocky",
        "created": "2019-10-02",
        "lastActive": "2024-06-20",
        "description": "I am full of energy and love to play in the yard",
        "city": "Dallas",
        "country": "United States",
        "image": "/images/m2.jpeg"
    },
    {
        "email": "luna@test.com",
        "breed": "German Shepherd",
        "username": "luna",
        "gender": "female",
        "dateOfBirth": "2021-06-11",
        "name": "Luna",
        "created": "2021-08-05",
        "lastActive": "2024-06-19",
        "description": "I am a big dog with a big personality, and I love cuddles",
        "city": "Seattle",
        "country": "United States",
        "image": "/images/m3.jpeg"
    },
    {
        "email": "gino@test.com",
        "breed": "Belgian Malinois",
        "username": "gino",
        "gender": "male",
        "dateOfBirth": "2021-02-15",
        "name": "Gino",
        "created": "2021-04-01",
        "lastActive": "2024-06-18",
        "description": "I enjoy hiking and playing fetch!",
        "city": "San Antonio",
        "country": "United States",
        "image": "/images/m4.jpeg"
    },
    {
        "email": "blue@test.com",
        "breed": "Blue Heeler",
        "username": "blue",
        "gender": "male",
        "dateOfBirth": "2020-01-05",
        "name": "Blue",
        "created": "2020-03-10",
        "lastActive": "2024-06-21",
        "description": "I love going on adventures and playing with my toys",
        "city": "Houston",
        "country": "United States",
        "image": "/images/m5.jpeg"
    }
];